name: "Debug APK Publisher"
branding:
  icon: "package"
  color: "red"
description: "Build & Publish Debug APK on Github"
author: "ShaunLWM"
inputs:
  GITHUB_TOKEN:
    required: true
    description: "Github secret token to allow automated publishing of APK to release."
  BUILD_TYPE:
    required: true
    description: "Choose build type [release/debug]"
  BUILD_FLAVOR:
    required: true
    description: "Choose build flavor [github/googlePlay]"
  TAG_SUFFIX:
    required: false
    description: "Suffix to append to tag name"
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"