name: Android CI

on:
  pull_request:
    branches: [ "master", "release" ]

jobs:
  build:
    name: 'Build check'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build apk
      run: ./gradlew assembleGithubDebug
