name: Android CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: 'Publish debug build'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - uses: actions/checkout@v3
      - name: Releasing using Hub
        uses: ./.github/actions/publish-release-apk
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          APP_FOLDER: app
          RELEASE_TITLE: Debug Build
          REPO_BRANCH: master
          BUILD_TYPE: debug
          GRADLEW_CONFIG: assembleDebug
