name: Android CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: 'Publish debug build'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Releasing using Hub
        uses: ./.github/actions/publish-release-apk
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          APP_FOLDER: app
          RELEASE_TITLE: Debug Build
          REPO_BRANCH: master
          BUILD_TYPE: debug
          GRADLEW_CONFIG: assembleDebug