name: Android CI

on:
  push:
    branches: [ "release" ]

jobs:
  build:
    name: 'Build release'

    runs-on: ubuntu-latest
    environment: release

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Config local properties
      env:
        RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
        RELEASE_STORE_KEY: ${{ secrets.RELEASE_STORE_KEY }}
        RELEASE_STORE_KEY_PASSWORD: ${{ secrets.RELEASE_STORE_KEY_PASSWORD }}
      run: echo releaseStorePassword=\"RELEASE_STORE_PASSWORD\" >> ./local.properties
           echo releaseKeyAlias=\"RELEASE_STORE_KEY\" >> ./local.properties
           echo releaseKeyPassword=\"RELEASE_STORE_KEY_PASSWORD\" >> ./local.properties
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - name: Releasing using Hub
      uses: Semper-Viventem/action-release-debugapk@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        APP_FOLDER: app
        RELEASE_TITLE: Debug Build
        REPO_BRANCH: release