name: Android CI

on:
  push:
    branches: [ "release" ]

jobs:
  build:
    name: 'Publish debug build'

    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_STORE_PATH: ${{ secrets.RELEASE_STORE_PATH }}
          RELEASE_STORE_KEY: ${{ secrets.RELEASE_STORE_KEY }}
          RELEASE_STORE_KEY_PASSWORD: ${{ secrets.RELEASE_STORE_KEY_PASSWORD }}
        run: ./gradlew assembleGithubRelease
      - name: Releasing using Hub
        uses: ./.github/actions/publish-release-apk
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          APP_FOLDER: app
          RELEASE_TITLE: Release Build
          REPO_BRANCH: release
          BUILD_TYPE: release
          BUILD_FLAVOR: github